-- inserts de la tabla  wp_subgrupos_test 

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,1,'Los libros son muy importantes para mí.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,2,'Oigo las palabras en mi mente antes de leer, hablar o escribir.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,3,'Me aportan más la radio o unas grabaciones que la televisión o las películas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,4,'Me gustan los juegos de palabras como el Scrabble, Anagrams o Password.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,5,'Me gusta entretenerme o entretener a los demás con trabalenguas, rimas absurdas o juegos de palabras.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,6,'En ocasiones, algunas personas me piden que les explique el significado de las palabras que utilizo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,7,'En el colegio asimilo mejor la Lengua y literatura, las Ciencias sociales y la Historia que las Matemáticas y las Ciencias naturales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,8,'Aprender a hablar o a leer otra lengua (inglés, francés…) me resulta relativamente sencillo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,9,'Mi conversación incluye referencias frecuentes a datos que he leído o escuchado. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 1,10,'Recientemente he escrito algo de lo que estoy especialmente orgulloso/a o que me ha aportado el reconocimiento de los demás. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,1,'Soy capaz de calcular operaciones mentalmente sin esfuerzo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,2,'Las Matemáticas y/o las Ciencias naturales figuran entre mis asignaturas favoritas en el colegio. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,3,'Me gustan los juegos o acertijos que requieren un pensamiento lógico.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,4,'Me gusta realizar experimentos del tipo: «¿Qué pasaría si…?».',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,5,'Mi mente busca patrones, regularidad o secuencias lógicas en las cosas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,6,'Me interesan los avances científicos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,7,'Creo que casi todo tiene una explicación racional.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,8,'En ocasiones pienso en conceptos claros, abstractos, sin palabras ni imágenes.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,9,'Me gusta detectar defectos lógicos en las cosas que la gente dice y hace.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 2,10,'Me siento más cómodo cuando las cosas están medidas, categorizadas, analizadas o cuantificadas de algún modo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,1,'Me gusta ir de excursión, el senderismo o, simplemente, pasear en plena naturaleza. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,2,'Pertenezco a una asociación de voluntarios relacionada con la naturaleza e intento ayudar para frenar la destrucción del planeta. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,3,'Me encanta tener animales en casa.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,4,'Tengo una afición relacionada de algún modo con la naturaleza (por ejemplo, la observación de aves). ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,5,'He asistido a cursos relacionados con la naturaleza.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,6,'Se me da bastante bien describir las diferencias entre distintos tipos de árboles, perros, pájaros u otras especies de flora o fauna. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,7,'Me gusta leer libros o revistas, o ver programas de televisión o películas, en los que la naturaleza esté presente. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,8,'Cuando tengo vacaciones, prefiero los entornos naturales (parques, campings, rutas de senderismo) a los hoteles / complejos turísticos y a los destinos urbanos  o culturales. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,9,'Me encanta visitar zoos, acuarios y demás lugares donde se estudie el mundo natural. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 3,10,'Tengo un jardín y disfruto cuidándolo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,1,'Cuando cierro los ojos percibo imágenes visuales claras.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,2,'Soy sensible al color.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,3,'Habitualmente utilizo una cámara de fotos o una cámara de vídeo para captar lo que veo a mí alrededor. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,4,' Me gustan los rompecabezas, los laberintos y demás juegos visuales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,5,'Por la noche tengo sueños muy intensos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,6,'En general, soy capaz de orientarme en un lugar desconocido.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,7,'Me gusta dibujar o garabatear.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,8,'Lo que más me gusta de las Matemáticas es la geometría.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,9,'Puedo imaginar sin ningún esfuerzo el aspecto que tendrían las cosas vistas desde arriba. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 4,10,'Prefiero el material de lectura con muchas ilustraciones.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,1,'Tengo una voz agradable.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,2,'Percibo cuando una nota musical está desafinada.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,3,'Siempre estoy escuchando música.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,4,'Toco un instrumento musical.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,5,'Sin la música, mi vida sería más triste.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,6,'En ocasiones, cuando voy por la calle, me sorprendo cantando mentalmente la música de un anuncio de televisión o alguna otra melodía. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,7,'Puedo seguir fácilmente el ritmo de un tema musical con un instrumento de percusión. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,8,'Conozco las melodías de numerosas canciones o piezas musicales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,9,'Con solo escuchar una selección musical una o dos veces, ya soy capaz de reproducirla con bastante acierto. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 5,10,'Acostumbro a producir sonidos rítmicos con golpecitos o a cantar melodías mientras estoy trabajando, estudiando, o aprendiendo algo nuevo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,1,'Practico al menos un deporte o algún tipo de actividad física de forma regular.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,2,'Me cuesta permanecer quieto durante mucho tiempo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,3,'Me gusta trabajar con las manos en actividades concretas como coser, tejer, tallar, la carpintería, o la construcción de maquetas. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,4,'En general, las mejores ideas se me ocurren cuando estoy paseando o corriendo, o mientras realizo alguna actividad física. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,5,'Me gusta pasar mí tiempo de ocio al aire libre.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,6,'Acostumbro a gesticular mucho o a utilizar otras formas de lenguaje corporal cuando hablo con alguien. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,7,'Necesito tocar las cosas para saber más sobre ellas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,8,'Me gustan las atracciones fuertes y las experiencias físicas emocionantes.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,9,'Creo que soy una persona con una buena coordinación.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 6,10,'No me basta con leer información o ver un vídeo sobre una nueva actividad: necesito practicarla. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,1,'Practico al menos un deporte o algún tipo de actividad física de forma regular.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,2,'He asistido a sesiones de asesoramiento o seminarios de crecimiento personal para aprender a conocerme más. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,3,'Soy capaz de afrontar los contratiempos con fuerza moral.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,4,'Tengo una afición especial o una actividad que guardo para mí.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,5,'Tengo algunos objetivos vitales importantes en los que pienso de forma habitual.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,6,'Mantengo una visión realista de mis puntos fuertes y débiles (confirmados mediante el contraste con otras fuentes). ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,7,'Preferiría pasar un fin de semana solo en una cabaña, en el bosque, que en lugar turístico de lujo lleno de gente. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,8,'Me considero una persona con mucha fuerza de voluntad o independiente.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,9,'Escribo un diario personal en el que recojo los pensamientos relacionados con mi vida interior. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 7,10,'Cuando sea mayor, me gustaría poner en marcha mi propio negocio.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,1,'Soy del tipo de personas a los que los demás piden opinión y consejo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,2,'Prefiero los deportes de equipo a los deportes solitarios.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,3,'Cuando tengo un problema, tiendo a buscar la ayuda de otra persona en lugar de intentar resolverlo por mí mismo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,4,'Tengo al menos tres amigos íntimos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,5,'Me gustan más los juegos sociables, como el Monopoly o las cartas, que las actividades que se realizan en solitario, como los videojuegos. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,6,'Disfruto con el reto que supone enseñar a algo qué sé hacer otra persona, o grupos de personas. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,7,'Me considero un líder (o los demás me dicen que lo soy).',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,8,'Me siento cómodo entre una multitud.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,9,'Me gusta participar en actividades sociales relacionadas con mi trabajo, con la parroquia o con la comunidad. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (1, 8,10,'Prefiero pasar una tarde en una fiesta animada que solo en casa.',1);

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,1,'Para mi es importante recibir la aprobación de los demás ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,2,'Me gusta que los demás me respeten, pero yo no tengo por qué manifestar respeto a nadie',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,3,'Quiero gustar a todo el mundo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,4,'Me cuesta gustarme a mí mismo, aun cuando no guste a los demás',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,5,'Si no gusto a los demás me genera un problema con migo mismo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,6,'Pienso que es duro ir en contra de lo que piensan los demás',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,7,'Me gusta recibir la aprobación de los demás, tengo necesidad real de ello',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,8,'A menudo me preocupa que la gente me apruebe y me acepte',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,9,'Tengo considerable preocupación por lo que la gente piense de mi',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 1,10,'Ser criticado es algo fastidioso y perturbador',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,1,'Odio equivocarme en algo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,2,'Evito las cosas que no puedo hacer bien ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,3,'Me gusta competir en aquellas actividades en las que los demás son mejores que yo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,4,'Me gustaría triunfar en algo, pienso que debo hacerlo ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,5,'Para mí es muy importante lograr el éxito en todo lo que hago',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,6,'Disfruto de las actividades por sí mismas, pero no disfruto tanto si es que soy malo/a en ellas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,7,'Me fastidia que los demás sean mejores que yo en algo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,8,'Me trastorna cometer errores ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,9,'Muchas veces me enfado muchísimo por cosas sin importancia',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 2,10,'Me asusta hacer aquellas cosas que no hago del todo bien',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,1,'La gente que se equivoca, logra lo que se merece ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,2,'Hay demasiadas personas malas que escapan del castigo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,3,'Aquellos que se equivocan, merecen cargar con las culpas ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,4,'La inmoralidad debería castigarse severamente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,5,'Suelo culpar a la gente de sus errores',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,6,'El miedo al castigo es lo que hace a la gente ser buena ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,7,'Todo el mundo es, esencialmente, bueno',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,8,'No es equitativo "llueva igual sobre el justo que sobre el injusto"',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,9,'Generalmente NO doy una segunda oportunidad a quien se equivoca',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 3,10,'Las personas son malas si sus actos asi lo muestran ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,1,'Generalmente, NO acepto los acontecimientos con filosofía',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,2,'Las frustraciones me distorsionan',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,3,'Las cosas deberían ser distintas a como son',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,4,'A menudo me siento trastornado/a por situaciones que no me gustan ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,5,'Normalmente, No acepto las cosas como son, aunque no me gusten',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,6,'Si las cosas me desagradan NO opto por ignorarlas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,7,'No hago todo lo que puedo por conseguir lo que quiero ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,8,'Yo NO disfruto honradamente de la vida',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,9,'La gente es más feliz cuando tiene metas y problemas que resolver ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 4,10,'Generalmente me importunan los errores de los demás',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,1,'Por mas que una persona quiera, puede llegar a NO ser feliz en casi cualquier circunstancia',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,2,'A la gente le trastornan los acontecimientos cualquiera sean',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,3,'Los demas provocan mi propio mal humor',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,4,'Las personas desgraciadas, normalmente se deben este estado a los demas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,5,'No depende de uno quedar de mal humor por mucho tiempo , sino que depende del tamaño de bronca o acto que lo generó',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,6,'Cuanto más problemas tiene una persona, menos feliz es',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,7,'Todo lo externo puede ser perturbador, no depende de como yo lo tome, depende del acto externo en sí',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,8,'Debería haber más personas que afrontaran lo desagradable de la vida ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,9,'Siempre hay razón para permanecer afligido mucho tiempo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 5,10,'El hombre NO construye su propio malestar interno',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,1,'Temo a las cosas que, a menudo, me resultan objeto de preocupación ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,2,'Me producen ansiedad los peligros inesperados o los acontecimientos futuros',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,3,'A menudo, no puedo quitarme algún asunto de la cabeza',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,4,'Me preocupo por no poder evitar que algo ocurra ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,5,'No puedo soportar correr riesgos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,6,'Generalmente me siento ansioso/a al pensar en el futuro ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,7,'Me preocupan mucho determinadas cosas del futuro',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,8,'Algunas veces, me resulta imposible apartar de mi mente el miedo a algo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,9,'Frecuentemente pienso en cosas como la muerte',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 6,10,'Muchas veces me sorprendo planeando lo que haría si me encontrara en determinadas situaciones de peligro',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,1,'Normalmente, aplazo las decisiones importantes',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,2,'Trato de evitar afrontar los trabajos fastidiosos y demoro en hacerlos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,3,'Evito enfrentarme a los problemas ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,4,'Normalmente, NO tomo las decisiones tan pronto como puedo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,5,'La vida es demasiado corta para pasarla haciendo cosas que a uno no le gustan',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,6,'Generalmente aplazo las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,7,'Me resulta difícil hacer las tareas desagradables ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,8,'Una vida fácil, resulta compensadora ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,9,'Me gustan las responsabilidades',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 7,10,'Si tengo que hacer algo que no me agrade, No lo Hago',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,1,'Todo el mundo necesita de alguien a quien recurrir en busca de ayuda y concejo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,2,'En las decisiones importantes, consulto con una autoridad al respecto ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,3,'Todo el mundo necesita tener fuera de sí mismo una fuente de energía',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,4,'Hay determinadas personas de las que dependo mucho',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,5,'No me gusta valerme por mi mismo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,6,'Yo no puedo entender y solucionar mis problemas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,7,'Me agrada que los demás tomen decisiones por mi ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,8,'Pienso que es fácil buscar ayuda',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,9,'Me gusta depender de los demás',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 8,10,'He aprendido a estar pendiente de lo que no este relacionado con mi bienestar',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,1,' Una cebra no puede cambiar sus rayas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,2,'Es casi imposible superar la influencia del pasado ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,3,'Si algo afecto tu vida de forma importante, significa que va a ser igual en el futuro',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,4,'La gente No sobrevalora la influencia del pasado',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,5,'Si hubiera vivido experiencias distintas, podría ser mas como me gustaría ser ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,6,'Nunca pienso que las experiencias pasadas me afectan en la actualidad',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,7,'Somos esclavos de nuestro pasado',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,8,'Cada vez que algo afecta tu vida de forma importante, seguirá haciéndolo siempre',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,9,'La gente nunca cambia, básicamente ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 9,10,'Miro atrás con resentimiento',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,1,'Prefiero, sobre todas las cosas, pasar el tiempo libre de una forma tranquila ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,2,'No me gusta disponer de muchos recursos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,3,'No me siento más satisfecho cuando tengo muchas cosas que hacer',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,4,'Lo que menos me divierte es realizar algún proyecto creativo ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,5,'Me gustaría jubilarme y apartarme totalmente del trabajo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,6,'Tener demasiado tiempo libre, resulta divertido',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,7,'A veces desearía poder irme a una isla tropical y tenderme en la playa, sin hacer nada mas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,8,'Me encanta estar acostado',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,9,'La mayoría de la gente trabaja demasiado y no descansa lo suficiente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (2, 10,10,'No me siento contento/a hasta que no estoy relajado y sin hacer nada',1);

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 1,1,'Dibujar casar, objetos, figuras humanas, etcétera. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 1,2,'Pintar paisajes.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 1,3,'Decorar artísticamente un salón, corredor, escenario o patio para un festival. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 1,4,'Modelar con barro, plastilina o grabar madera. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 1,5,'Distinguir y apreciar la buena pintura.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 1,6,'Colaborar en la elaboración de un libro sobre el arte en la Arquitectura.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 2,1,'Ejecutar con rapidez y exactitud operaciones aritméticas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 2,2,'Resolver problemas de aritmética.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 2,3,'Resolver rompecabezas numéricos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 2,4,'Resolver problemas de álgebra.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 2,5,'Resolver problemas de geometría.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 2,6,'Enseñar a resolver problemas de matemáticas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 3,1,'Entender principios y experimentos de biología.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 3,2,'Entender principios y experimentos de física. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 3,3,'Entender principios y experimentos de química.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 3,4,'Entender principios y hechos económicos y sociales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 3,5,'Entender las causas que determinan los acontecimientos históricos. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 3,6,'Realizar investigaciones científicas teniendo como finalidad la búsqueda de la verdad.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 4,1,'Ser jefe competente de un grupo, equipo o sociedad. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 4,2,'Organizar y dirigir festivales, encuentros deportivos, excursiones o campañas sociales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 4,3,'Convencer a otros para que hagan lo que crees que deben hacer. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 4,4,'Dar órdenes a otros con seguridad y naturalidad. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 4,5,'Dirigir un grupo o equipo en situaciones difíciles o peligrosas. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 4,6,'Corregir a los demás sin ofenderlos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 5,1,'Armar y componer objetos mecánicos como chapas, timbres, etcétera. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 5,2,'Desarmar, armar y componer objetos complicados. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 5,3,'Resolver rompecabezas de alambre o de madera.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 5,4,'Armar y componer muebles. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 5,5,'Aprender el funcionamiento de ciertos mecanismos complicados como motores, relojes, bombas, etcétera. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 5,6,'Inducir a las personas a obtener resultados prácticos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 6,1,'Cantar en un grupo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 6,2,'Tocar un instrumento musical.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 6,3,'Distinguir cuando alguien desentona en las canciones o piezas musicales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 6,4,'Entonar correctamente las canciones de moda.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 6,5,'Distinguir y apreciar la buena música.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 6,6,'Dirigir un grupo musical.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 7,1,'Llevar en forma correcta y ordenada los apuntes de clase.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 7,2,'Ordenar y clasificar debidamente documentos en una oficina.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 7,3,'Contestar y redactar correctamente oficios y cartas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 7,4,'Anotar y manejar con exactitud y rapidez nombres, números y otros datos. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 7,5,'Encargarse de recibir, anotar y dar recados sin olvidar detalles importantes.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 7,6,'Colaborar en el desarrollo de métodos más eficientes de trabajo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 8,1,'Tratar y hablar con sensibilidad a las personas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 8,2,'Ser miembro activo y útil en un club o sociedad. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 8,3,'Colaborar con otros para el bien de la comunidad ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 8,4,'Saber escuchar a otros con paciencia y comprender su punto de vista.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 8,5,'Conversar en las reuniones y fiestas con acierto y naturalidad.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 8,6,'Actuar con desinterés.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 9,1,'Actividades que requieren destreza manual.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 9,2,'Manejar con habilidad herramienta de carpintería.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 9,3,'Manejar con facilidad herramientas mecánicas como pinzas, llaves de tuercas, desarmador, etcétera.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 9,4,'Manejar con habilidad pequeñas piezas y herramientas como agujas, manecillas, joyas, piezas de relojería, etcétera. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 9,5,'Hacer con facilidad trazos geométricos con la ayudad de las escuadras, la regla “T” y compás.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 9,6,'Participar en un concurso de modelismo de coches, aviones, barcos, etcétera.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 10,1,'Expresarte con facilidad en clase o al platicar con tus amigos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 10,2,'Redactar composiciones o artículos periodísticos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 10,3,'Componer versos serios o jocosos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 10,4,'Escribir cuentos, narraciones o historietas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 10,5,'Distinguir y apreciar la buena literatura.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (3, 10,6,'Exponer juicios públicamente sin preocupación por la crítica.',1);

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 1,1,'Dibujar y pintar ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 1,2,'Moldear el barro, plastilina o cualquier otro material.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 1,3,'Encargarte del decorado del lugar para un festival.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 1,4,'Idear y diseñar el escudo de un club o sociedad.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 1,5,'Diseñar el vestuario para una función teatral. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 1,6,'Dibujante profesional en una empresa.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 2,1,'Resolver cuestionarios de matemáticas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 2,2,'Resolver problemas de aritmética.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 2,3,'Llevar las cuentas de una institución. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 2,4,'Explicar a otros cómo resolver problemas de matemáticas. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 2,5,'Participar en concursos de matemáticas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 2,6,'Experto calculista en una institución. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 3,1,'Conocer y estudiar la estructura de las plantas y de los animales. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 3,2,'Hacer experimentos en un laboratorio.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 3,3,'Investigar el origen de las costumbres de los pueblos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 3,4,'Estudiar y entender las causas de los movimientos sociales.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 3,5,'Leer revistas y libros científicos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 3,6,'Investigar en un laboratorio.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 4,1,'Intervenir activamente en las discusiones de clase.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 4,2,'Ser jefe de un grupo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 4,3,'Dirigir la campaña política para un candidato estudiantil. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 4,4,'Hacer propaganda para la difusión de una idea. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 4,5,'Leer biografías de políticos eminentes. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 4,6,'Experto en relaciones sociales de una gran empresa.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 5,1,'Armar y desarmar objetos mecánicos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 5,2,'Manejar herramientas y maquinaria.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 5,3,'Construir objeto o muebles.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 5,4,'Reparar las instalaciones eléctricas, de gas o de plomería en tu casa. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 5,5,'Proyectar y dirigir alguna construcción.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 5,6,'Perito mecánico en un taller.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 6,1,'Cantar en un coro estudiantil.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 6,2,'Escuchar música todo tipo de música.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 6,3,'Aprender a tocar un instrumento musical.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 6,4,'Ser miembro de una asociación musical.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 6,5,'Leer biografías de músicos eminentes. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 6,6,'Concertista en una sinfónica.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 7,1,'Llevar en orden tus libros y cuadernos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 7,2,'Ordenar y clasificar los libros de una biblioteca.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 7,3,'Aprender a escribir a máquina.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 7,4,'Ayudar a calificar pruebas. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 7,5,'Encargarte del archivo y los documentos de una sociedad. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 7,6,'Técnico organizador de oficinas.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 8,1,'Atender y cuidar enfermos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 8,2,'Proteger a los menores del grupo. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 8,3,'Ser miembro de una sociedad de ayuda y asistencia.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 8,4,'Enseñar a leer a los analfabetos. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 8,5,'Ayudar a tus compañeros en sus dificultades y preocupaciones. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 8,6,'Funcionario al servicio de las clases humildes.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 9,1,'Salir de excursión. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 9,2,'Pertenecer a un grupo de exploradores. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 9,3,'Trabajar al aire libre, fuera de la ciudad.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 9,4,'Sembrar y plantar en una granja durante las vacaciones. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 9,5,'Atender animales en un rancho durante las vacaciones. ',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 9,6,'Técnico cuyas actividades se desempeñan fuera de la ciudad.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 10,1,'Escribir cuentos, crónicas o artículos.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 10,2,'Leer obras literarias.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 10,3,'Hacer versos para una publicación.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 10,4,'Representar un papel en una obra de teatro.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 10,5,'Participar en un concurso de oratoria.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (4, 10,6,'Escritor en un periódico o empresa editorial.',1);

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,1,'Muchas veces actúo sin mirar las consecuencias.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,2,'Creo que los formalismos coartan y limitan la actuación libre de las personas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,3,'Pienso que el actuar intuitivamente puede ser siempre tan válido como actuar reflexivamente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,4,'Procuro estar al tanto de lo que ocurre aquí y ahora',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,5,'Prefiero las ideas originales y novedosas aunque no sean prácticas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,6,'Me entusiasmo con el reto de hacer algo nuevo y diferente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,7,'Me siento a gusto con personas espontáneas y divertidas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,8,'La mayoría de las veces expreso abiertamente cómo me siento',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,9,'Me gusta afrontar la vida espontáneamente y no tener que planificar todo previamente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,10,'Me siento incómodo/a con las personas calladas y demasiado analíticas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,11,'Es mejor gozar del momento presente que deleitarse pensando en el pasado o en el futuro',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,12,'Aporto ideas nuevas y espontáneas en los grupos de discusión',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,13,'Creo que es preciso saltarse las normas muchas más veces que cumplirlas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,14,'En conjunto hablo más de lo que escucho',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,15,'Me gusta buscar nuevas experiencias',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,16,'Cuando algo va mal, le quito importancia y trato de hacerlo mejor',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,17,'Me resulta incómodo tener que planificar y prever las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,18,'Con frecuencia soy una de las personas que más anima las fiestas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,19,'Me aburro enseguida con el trabajo metódico y minucioso',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 1,20,'Suelo dejarme llevar por mis intuiciones',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,1,'Estoy seguro/a de lo que es bueno y lo que es malo, lo que está bien y lo que está mal',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,2,'Normalmente trato de resolver los problemas metódicamente y paso a paso.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,3,'Me interesa saber cuáles son los sistemas de valores de los demás y con qué criterios actúan',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,4,'Estoy a gusto siguiendo un orden en las comidas, en el estudio, haciendo ejercicio regularmente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,5,'Normalmente encajo bien con personas reflexivas, y me cuesta sintonizar con personas demasiado espontáneas, imprevisibles',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,6,'Prefiero las cosas estructuradas a las desordenadas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,7,'Casi siempre procuro ser coherente con mis criterios y sistemas de valores. Tengo principios y los sigo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,8,'Me disgusta implicarme afectivamente en el ambiente de la escuela. Prefiero mantener relaciones distantes',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,9,'Me cuesta ser creativo/a, romper estructuras',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,10,'Me molesta que la gente no se tome en serio las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,11,'Tiendo a ser perfeccionista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,12,'Detecto frecuentemente la inconsistencia y puntos débiles en las argumentaciones de los demás',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,13,'Estoy convencido/a que debe imponerse la lógica y el razonamiento',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,14,'Siempre trato de conseguir conclusiones e ideas claras',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,15,'Observo que, con frecuencia, soy uno/a de los/as más objetivos/as y desapasionados/as en las discusiones',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,16,'Con frecuencia miro hacia delante para prever el futuro',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,17,'Me molestan las personas que no actúan con lógica',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,18,'Ante los acontecimientos trato de descubrir los principios y teorías en que se basan',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,19,'Si trabajo en grupo procuro que se siga un método y un orden',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 2,20,'Esquivo los temas subjetivos, ambiguos y poco claros',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,1,'Tengo fama de decir lo que pienso claramente y sin rodeos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,2,'Creo que lo más importante es que las cosas funcionen',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,3,'Cuando escucho una nueva idea enseguida comienzo a pensar cómo ponerla en práctica',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,4,'Admito y me ajusto a las normas sólo si me sirven para lograr mis Objetivos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,5,'Cuando hay una discusión no me gusta ir con rodeos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,6,'Me gustan más las personas realistas y concretas que las teóricas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,7,'Me atrae experimentar y practicar las últimas técnicas y novedades',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,8,'Juzgo con frecuencia las ideas de los demás por su valor práctico',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,9,'En las reuniones apoyo las ideas prácticas y realistas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,10,'A menudo caigo en la cuenta de otras formas mejores y más prácticas de hacer las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,11,'Me gusta experimentar y aplicar las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,12,'Pienso que debemos llegar pronto al grano, al meollo de los temas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,13,'Me impaciento cuando me dan explicaciones irrelevantes e incoherentes',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,14,'Compruebo antes si las cosas funcionan realmente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,15,'Soy consciente de que en las discusiones ayudo a mantener a los demás centrados en el tema, evitando divagaciones',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,16,'Rechazo ideas originales y espontáneas si no las veo prácticas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,17,'Creo que el fin justifica los medios en muchos casos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,18,'Con tal de conseguir el objetivo que pretendo soy capaz de herir sentimientos ajenos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,19,'No me importa hacer todo lo necesario para que sea efectivo mi trabajo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 3,20,'La gente con frecuencia cree que soy poco sensible a sus sentimientos',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,1,'Disfruto cuando tengo tiempo para preparar mi trabajo y realizarlo a conciencia',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,2,'Escucho con más frecuencia que hablo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,3,'Cuando poseo cualquier información, trato de interpretarla bien antes de manifestar alguna conclusión',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,4,'Antes de hacer algo estudio con cuidado sus ventajas e inconvenientes',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,5,'Me gusta analizar y dar vueltas a las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,6,'Soy cauteloso/a a la hora de sacar conclusiones',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,7,'Prefiero contar con el mayor número de fuentes de información. Cuantos más datos reúna para reflexional, mejor',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,8,'Prefiero oír las opiniones de los demás antes de exponer la mía',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,9,'En las discusiones me gusta observar cómo actúan los demás participantes',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,10,'Me agobio si me obligan a acelerar mucho el trabajo para cumplir un plazo.',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,11,'Me molestan las personas que siempre desean apresurar las cosas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,12,'Pienso que son más consistentes las decisiones fundamentadas en un minucioso análisis que las basadas en la intuición',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,13,'Prefiero distanciarme de los hechos y observarlos desde otras perspectivas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,14,'Prefiero discutir cuestiones concretas y no perder el tiempo con charlas superficiales',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,15,'Hago varios borradores antes de la redacción definitiva de un trabajo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,16,'Me gusta analizar diversas alternativas antes de tomar una decisión',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,17,'En los debates y discusiones prefiero desempeñar un papel secundario antes que ser el/la líder o el/la que más participa',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,18,'Suelo reflexionar sobre los asuntos y problemas',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,19,'El trabajar a conciencia me llena de satisfacción y orgullo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (5, 4,20,'Con frecuencia me interesa averiguar lo que piensa la gente',1);

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,1,'Animado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,2,'Juguetón/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,3,'Sociable',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,4,'Convincente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,5,'Entsiasta',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,6,'Enérgico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,7,'Activista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,8,'Espontáneo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,9,'Optimista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,10,'Humorístico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,11,'Encantador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,12,'Alegre',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,13,'Inspirador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,14,'Cálido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,15,'Cordial',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,16,'Hablador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,17,'Vivaz',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,18,'Listo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,19,'Popular',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 1,20,'Jovial',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,1,'Aventurero/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,2,'Persuasivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,3,'Decidido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,4,'Competitivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,5,'Inventivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,6,'Autosuficiente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,7,'Positivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,8,'Seguro/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,9,'Abierto/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,10,'Dominante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,11,'Osado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,12,'Confiado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,13,'Independiente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,14,'Decisivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,15,'Instigador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,16,'Tenaz',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,17,'Lider',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,18,'Jefe',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,19,'Productivo/',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 2,20,'Atrevido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,1,'Analítico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,2,'Persistente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,3,'Abnegado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,4,'Considerado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,5,'Respetuoso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,6,'Sensible',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,7,'Fiel',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,8,'Puntual',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,9,'Ordenado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,10,'Planificador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,11,'Detallista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,12,'Culto/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,13,'Idealista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,14,'Instrospectivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,15,'Musical',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,16,'Leal',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,17,'Organizado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,18,'Perfeccionista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,19,'Tranquilo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 3,20,'Pacifico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,1,'Adaptable',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,2,'Plácido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,3,'Sumiso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,4,'Controlado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,5,'Reservado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,6,'Contento/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,7,'Paciente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,8,'Tímido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,9,'Atento/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,10,'Amigable',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,11,'Diplomatico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,12,'Constante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,13,'Consiliador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,14,'Tolerante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,15,'Sabe escuchar',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,16,'Contento/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,17,'Permisivo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,18,'Equilibrado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,19,'Humor seco',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (6, 4,20,'Inofensivo/a',1);

insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,1,'Estridente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,2,'Indiciplinado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,3,'Repetidor/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,4,'Olvidadizo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,5,'Interrumpo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,6,'Imprevisible',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,7,'Descuidado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,8,'Tolerante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,9,'Argumentador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,10,'Ingenuo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,11,'Hablador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,12,'Desordenado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,13,'Inconsistente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,14,'Ostentoso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,15,'Emocional',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,16,'Atolondrado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,17,'Inquieto/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,18,'Variable',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,19,'Egocéntrico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 1,20,'Desorganizado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,1,'Mandón/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,2,'Antipático/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,3,'Resistente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,4,'Franco/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,5,'Impaciente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,6,'Frío/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,7,'Terco/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,8,'Iracundo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,9,'Orgulloso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,10,'Nervioso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,11,'Adicto/a al trabajo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,12,'Indiscreto/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,13,'Dominante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,14,'Intolerante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,15,'Manipulador/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,16,'Testarudo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,17,'Prepotente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,18,'Malgeniado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,19,'Precipitado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 2,20,'Astuto/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,1,'Apocado/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,2,'Sin entusiasmo',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,3,'Resentido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,4,'Exigente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,5,'Inseguro/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,6,'No comprometido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,7,'Dificil de contentar',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,8,'Pesimista',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,9,'Sin motivación',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,10,'Negativo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,11,'Abstraído/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,12,'Seseptible',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,13,'Deprimido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,14,'Introvertido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,15,'Moroso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,16,'Escéptico/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,17,'Solitario/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,18,'Suspicaz',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,19,'Vengativo/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 3,20,'Comprometido',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,1,'Soso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,2,'Implacable',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,3,'Reticente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,4,'Temeroso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,5,'Indeciso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,6,'Impopular',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,7,'Vacilante',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,8,'Insípido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,9,'Taciturno/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,10,'Desprendido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,11,'Ansioso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,12,'Timido/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,13,'Dudoso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,14,'Indiferente',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,15,'Quejumbroso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,16,'Lento/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,17,'Perezoso/a',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,18,'Sin ambisión',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,19,'Poca Voluntad',1);
insert into wp_preguntas_test (tipo_test_id, subgrupo_test_id, numero_pregunta, texto, estado) values (7, 4,20,'Crítico/a',1);


